我给你升级成**能直观看到产生/湮灭算符作用**的完整版演示！
直接在态上作用：
- $a^\dagger|n\rangle = \sqrt{n+1}|n+1\rangle$ **升高能级**
- $a|n\rangle = \sqrt{n}|n-1\rangle$ **降低能级**

---


# 这个代码会**清晰展示**以下核心效果

## 1. 产生算符 $a^\dagger$
- $a^\dagger|0\rangle = \sqrt{1}|1\rangle$
- $a^\dagger|1\rangle = \sqrt{2}|2\rangle$
- $a^\dagger|2\rangle = 0$（三能级上限）

## 2. 湮灭算符 $a$
- $a|1\rangle = \sqrt{1}|0\rangle$
- $a|2\rangle = \sqrt{2}|1\rangle$
- $a|0\rangle = 0$（基态不能再湮灭）

## 3. 粒子数算符 $\hat{n}=a^\dagger a$
- $\hat{n}|0\rangle=0|0\rangle$
- $\hat{n}|1\rangle=1|1\rangle$
- $\hat{n}|2\rangle=2|2\rangle$

## 4. 画图直观看到：
每个态被作用后**粒子数分布的变化**
- 作用 $a^\dagger$ → 峰**右移**
- 作用 $a$ → 峰**左移**

---

### 总结
1. **产生算符**：把态**升高一级**
2. **湮灭算符**：把态**降低一级**
3. **粒子数算符**：直接读出能级 $n$
4. **哈密顿量**：给出等间距能级 $E=(n+1/2)\hbar\omega$

In [29]:
import qutip as qt
import numpy as np
from IPython.display import display

# 1. 定义参数和希尔伯特空间维度
N = 3  # 三能级系统
omega = 1.0  # 假设频率为 1
hbar = 1.0

# 2. 定义基本算符
a = qt.destroy(N)      # 湮灭算符
adag = qt.create(N)    # 产生算符
n = adag * a


# 3. 构建哈密顿量 H = hbar * omega * (n + 0.5)
H = hbar * omega * (n + 0.5 * qt.qeye(N))

print("哈密顿量 H:")
print(H)

# 4. 准备基态 |0>
psi0 = qt.basis(N, 0)
print(f"\n基态 |0>: \n{psi0}\n\n")





哈密顿量 H:
Quantum object: dims=[[3], [3]], shape=(3, 3), type='oper', dtype=Dia, isherm=True
Qobj data =
[[0.5 0.  0. ]
 [0.  1.5 0. ]
 [0.  0.  2.5]]

基态 |0>: 
Quantum object: dims=[[3], [1]], shape=(3, 1), type='ket', dtype=Dense
Qobj data =
[[1.]
 [0.]
 [0.]]




In [30]:
# 5. 演示产生算符的作用: adag |0> -> |1>
psi1 = adag * psi0
print(f'产生算符：\n {adag}')
print(f"产生算符作用于 |0> (adag * |0>): \n{psi1}\n\n")

产生算符：
 Quantum object: dims=[[3], [3]], shape=(3, 3), type='oper', dtype=Dia, isherm=False
Qobj data =
[[0.         0.         0.        ]
 [1.         0.         0.        ]
 [0.         1.41421356 0.        ]]
产生算符作用于 |0> (adag * |0>): 
Quantum object: dims=[[3], [1]], shape=(3, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [1.]
 [0.]]




In [31]:
# 6. 演示湮灭算符的作用: a |1> -> |0>
psi0_back = a * psi1
print(f'湮灭算符：\n {a}')
print(f"湮灭算符作用于 |1> (a * |1>): \n{psi0_back}\n\n")




湮灭算符：
 Quantum object: dims=[[3], [3]], shape=(3, 3), type='oper', dtype=Dia, isherm=False
Qobj data =
[[0.         1.         0.        ]
 [0.         0.         1.41421356]
 [0.         0.         0.        ]]
湮灭算符作用于 |1> (a * |1>): 
Quantum object: dims=[[3], [1]], shape=(3, 1), type='ket', dtype=Dense
Qobj data =
[[1.]
 [0.]
 [0.]]




In [32]:
# 7. 验证粒子数算符的作用: n |2> = 2|2>
psi2 = qt.basis(N, 2)

print(f"粒子数算符 n:\n {n}")
print(f"验证粒子数算符的态 |2:\n {psi2}")
print(f"验证粒子数算符在 |2> 上的期望值: {qt.expect(n, psi2)}")

粒子数算符 n:
 Quantum object: dims=[[3], [3]], shape=(3, 3), type='oper', dtype=Dia, isherm=True
Qobj data =
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 2.]]
验证粒子数算符的态 |2:
 Quantum object: dims=[[3], [1]], shape=(3, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [0.]
 [1.]]
验证粒子数算符在 |2> 上的期望值: 2.0000000000000004
